name: 'dispatch-workflow'
description: 'Trigger a workflow dispatch action and wait for the status check to succeed'
inputs:
  token: 
    description: 'Github Personal Access token'
    required: true
    type: string
  workflow: 
    description: 'Path to the dispatchable workflow'
    required: true
    type: string
runs:
  using: "composite"
  steps:
      - name: Trigger Workflow
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GH_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$GH_WORKFLOW/dispatches \
          -d '{"ref":"main","inputs":{"repository":"${{ github.repository }}"}}'
        env: 
          GH_TOKEN: ${{inputs.token}}
          GH_WORKFLOW: ${{inputs.workflow}}
